[project]
name = "ft_package"
version = "0.0.1"
description = "A sample test package"
readme = "README.md"
authors = [
    { name = "asoler", email = "asoler@42.fr" }
]
license = { text = "MIT" }

[project.urls]
"Home-page" = "https://github.com/angelasoler/python-for-data-science"
